import type { NextPage } from 'next';
import Head from 'next/head';
import { useMemo, useState } from 'react';
import ThemeContext, { ThemeOptions } from '@contexts/ThemeContext';
import NavLocationContext from '@contexts/NavLocationContext';
import { lightTheme, darkTheme, links } from '../components/sections/projectData';

// components
import Intro from '@components/sections/Intro';
import Navbar from '@components/Navbar';
import Skills from '@components/sections/Skills';
import Projects from '@components/sections/Projects';
import Contact from '@components/sections/Contact';
import Footer from '@components/Footer';

// styles
import styles from '@styles/styles.module.scss';

const Home: NextPage = () => {
  const [theme, setTheme] = useState(ThemeOptions.Dark);
  const [location, setLocation] = useState('');

  const themeStyle = useMemo(() => {
    return theme === ThemeOptions.Dark ? darkTheme : lightTheme;
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, setTheme, themeStyle }}>
      <NavLocationContext.Provider value={{ location, setLocation }}>
        <div style={themeStyle} className={styles.container}>
          <Head>
            {/* change your meta information here */}
            <title>Steve Vang Dev</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Navbar links={links} />
          <main>
            {/* add sections here */}
            <Intro />
            <Skills />
            <Projects />
            <Contact />
          </main>
          <Footer />
        </div>
      </NavLocationContext.Provider>
    </ThemeContext.Provider>
  );
};

export default Home;
