import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useMemo, useState } from 'react';
import Intro from '../components/Intro';
import Navbar from '../components/Navbar';
import ThemeContext, { ThemeOptions } from '../contexts/ThemeContext';
import Skills from '../components/Skills';
import styles from '../styles/styles.module.scss';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import NavLocationContext from '../contexts/NavLocationContext';

const links = [
  {
    name: 'me',
    path: '#intro',
  },
  {
    name: 'software',
    path: '#skills',
  },
  {
    name: 'projects',
    path: '#projects',
  },
  {
    name: 'contact',
    path: '#contact',
  },
];

const Home: NextPage = () => {
  const [theme, setTheme] = useState(ThemeOptions.Dark);
  const [location, setLocation] = useState('');

  const themeStyle = useMemo(() => {
    if (theme === ThemeOptions.Dark) {
      return {
        color: '#6EDB93',
        backgroundColor: '#1E1E1E',
      };
    } else {
      return {
        color: '#293241',
        backgroundColor: '#edede9',
      };
    }
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, setTheme, themeStyle }}>
      <NavLocationContext.Provider value={{ location, setLocation }}>
        <div style={themeStyle} className={styles.container}>
          <Head>
            <title>Steve Vang Dev</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Navbar links={links} />
          <main>
            <Intro />
            <Skills />
            <Projects />
            <Contact />
          </main>
          <Footer />
        </div>
      </NavLocationContext.Provider>
    </ThemeContext.Provider>
  );
};

export default Home;
