import type { NextPage } from 'next';
import Head from 'next/head';
import { useMemo, useState } from 'react';
import Intro from '../components/sections/Intro';
import Navbar from '../components/Navbar';
import ThemeContext, { ThemeOptions } from '../contexts/ThemeContext';
import Skills from '../components/sections/Skills';
import styles from '../styles/styles.module.scss';
import Projects from '../components/sections/Projects';
import Contact from '../components/sections/Contact';
import Footer from '../components/Footer';
import NavLocationContext from '../contexts/NavLocationContext';
import links from '../data/navigation';

const Home: NextPage = () => {
  const [theme, setTheme] = useState(ThemeOptions.Dark);
  const [location, setLocation] = useState('');

  // change your theme styles here
  const themeStyle = useMemo(() => {
    if (theme === ThemeOptions.Dark) {
      return {
        color: '#6EDB93',
        backgroundColor: '#0b132b',
      };
    } else {
      return {
        color: '#293241',
        backgroundColor: '#f0efeb',
      };
    }
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, setTheme, themeStyle }}>
      <NavLocationContext.Provider value={{ location, setLocation }}>
        <div style={themeStyle} className={styles.container}>
          <Head>
            {/* change your meta information here */}
            <title>Steve Vang Dev</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Navbar links={links} />
          <main>
            {/* add sections here */}
            <Intro />
            <Skills />
            <Projects />
            <Contact />
          </main>
          <Footer />
        </div>
      </NavLocationContext.Provider>
    </ThemeContext.Provider>
  );
};

export default Home;
